# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxyNwV38JHxuu7QK01c4lu3Ke0WSoBVQ
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.power import NormalIndPower
from statsmodels.stats.proportion import proportions_ztest
import matplotlib.pyplot as plt

RNG = np.random.default_rng(42)
# %matplotlib inline

N_DAYS = 21
START_DATE = pd.Timestamp("2026-06-01")
DAILY_SESSIONS_MEAN = 2000

P_MOBILE = 0.55
P_NEW_USER = 0.40

BUG_START_DAY = 1
BUG_END_DAY = 5
BUG_MOBILE_TREATMENT_BOOST = 0.30

BASE_CVR = {
    ("mobile", "new"): 0.062, ("mobile", "returning"): 0.081,
    ("desktop", "new"): 0.071, ("desktop", "returning"): 0.093,
}
TRUE_LIFT = {
    ("mobile", "new"): 0.058, ("mobile", "returning"): 0.048,
    ("desktop", "new"): 0.004, ("desktop", "returning"): -0.002,
}
BASE_LOAD_MS = {"mobile": 1850, "desktop": 1400}
TREATMENT_LOAD_REGRESSION = 0.085

def assign_arm(day, device):
    p_treat = 0.5
    if device == "mobile" and BUG_START_DAY <= day <= BUG_END_DAY:
        p_treat = min(0.95, 0.5 + BUG_MOBILE_TREATMENT_BOOST)
    return "treatment" if RNG.random() < p_treat else "control"

# quick check
[assign_arm(2, "mobile") for _ in range(10)]

import os

def simulate():
    rows = []
    session_id = 1
    for day in range(N_DAYS):
        date = START_DATE + pd.Timedelta(days=day)
        n_sessions = RNG.poisson(DAILY_SESSIONS_MEAN)
        p_mobile_today = P_MOBILE
        p_new_today = P_NEW_USER
        if BUG_START_DAY <= day <= BUG_END_DAY:
            p_mobile_today = min(0.75, P_MOBILE + 0.12)
            p_new_today = min(0.60, P_NEW_USER + 0.10)

        for _ in range(n_sessions):
            device = "mobile" if RNG.random() < p_mobile_today else "desktop"
            user_type = "new" if RNG.random() < p_new_today else "returning"
            arm = assign_arm(day, device)

            base = BASE_CVR[(device, user_type)]
            lift = TRUE_LIFT[(device, user_type)] if arm == "treatment" else 0.0
            p_convert = np.clip(base + lift, 0.001, 0.999)
            converted = RNG.random() < p_convert

            base_load = BASE_LOAD_MS[device]
            mult = (1 + TREATMENT_LOAD_REGRESSION) if arm == "treatment" else 1.0
            page_load_ms = RNG.lognormal(mean=np.log(base_load * mult), sigma=0.22)

            rows.append({"session_id": session_id, "date": date, "day_index": day,
                          "device": device, "user_type": user_type, "arm": arm,
                          "converted": int(converted), "page_load_ms": round(page_load_ms, 1)})
            session_id += 1
    return pd.DataFrame(rows)

df = simulate()

# Create the 'data' directory if it doesn't exist
output_dir = "data"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, "checkout_sessions.csv"), index=False)
df.shape

df.groupby(["device", "arm"]).size().unstack()

def srm_check(df):
    results = {}
    overall = df["arm"].value_counts()
    chi2, p = stats.chisquare(overall.values)
    results["overall"] = {"counts": overall.to_dict(), "p_value": p, "srm_flag": p < 0.01}
    for device, sub in df.groupby("device"):
        counts = sub["arm"].value_counts()
        chi2, p = stats.chisquare(counts.values)
        results[f"device={device}"] = {"counts": counts.to_dict(), "p_value": p, "srm_flag": p < 0.01}
    return results

srm_check(df)

cvr = df.groupby("arm")["converted"].mean()
naive_lift_pp = (cvr["treatment"] - cvr["control"]) * 100
cvr, naive_lift_pp

def segment_analysis(df):
    rows = []
    for (device, user_type), sub in df.groupby(["device", "user_type"]):
        ctrl = sub[sub.arm == "control"]; treat = sub[sub.arm == "treatment"]
        n_c, n_t = len(ctrl), len(treat)
        x_c, x_t = ctrl["converted"].sum(), treat["converted"].sum()
        cvr_c, cvr_t = x_c / n_c, x_t / n_t
        z_stat, p_val = proportions_ztest(np.array([x_t, x_c]), np.array([n_t, n_c]))
        rows.append({"device": device, "user_type": user_type,
                      "n_control": n_c, "n_treatment": n_t,
                      "cvr_control": cvr_c, "cvr_treatment": cvr_t,
                      "lift_pp": (cvr_t - cvr_c) * 100, "p_value": p_val,
                      "significant": p_val < 0.05})
    return pd.DataFrame(rows)

seg = segment_analysis(df)
seg

def power_analysis(df, mde=0.015, alpha=0.05):
    analysis = NormalIndPower()
    rows = []
    for (device, user_type), sub in df.groupby(["device", "user_type"]):
        ctrl = sub[sub.arm == "control"]
        n_c, n_t = len(ctrl), len(sub[sub.arm == "treatment"])
        n_per_arm = min(n_c, n_t)
        p_base = ctrl["converted"].mean()
        h = 2*np.arcsin(np.sqrt(p_base+mde)) - 2*np.arcsin(np.sqrt(p_base))
        power = analysis.solve_power(effect_size=h, nobs1=n_per_arm, alpha=alpha, ratio=1.0, alternative="two-sided")
        rows.append({"device": device, "user_type": user_type, "n_per_arm": n_per_arm,
                      "achieved_power": power, "adequately_powered": power >= 0.80})
    return pd.DataFrame(rows)

power = power_analysis(df)
power

log_load = np.log(df["page_load_ms"])
ctrl_load = log_load[df.arm == "control"]
treat_load = log_load[df.arm == "treatment"]
t_stat, p_val = stats.ttest_ind(treat_load, ctrl_load, equal_var=False)

med_c = df.loc[df.arm=="control","page_load_ms"].median()
med_t = df.loc[df.arm=="treatment","page_load_ms"].median()
pct_change = (med_t - med_c)/med_c*100
med_c, med_t, pct_change, p_val

fig, ax = plt.subplots(figsize=(7,4))
pivot = seg.pivot(index="user_type", columns="device", values="lift_pp")
pivot.plot(kind="bar", ax=ax)
ax.axhline(0, color="gray", linestyle="--")
ax.set_ylabel("Lift (pp)")
ax.set_title("True Lift by Segment")
plt.show()

import os

output_dir = "outputs"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

seg.to_csv(os.path.join(output_dir, "segment_results.csv"), index=False)
power.to_csv(os.path.join(output_dir, "power_results.csv"), index=False)

